### ISSUE TITLE
Is it possible to add the extension to txt2img?

### ISSUE THREAD

**Issue by GlebIgorevich** [Haoming02/sd-webui-dynamic-hdr#1]
This extension looks helpful. Could you add the support for text-to-image generation because drawing form 0 with it is better than editing an image with it?

**Comment by Haoming02** [comment]
Well... As mentioned in the `README`, this Extension does absolutely nothing with the actual **Stable Diffusion** pipeline. It basically alters the input image right before sending it into **img2img**.

**TL;DR:** This Extension is dumb. And porting to **txt2img** is not planned in the near future.

**Comment by Haoming02** [comment]
*If you want to generate high contrast images in **txt2img**, check out [Noise Offset](https://civitai.com/models/13941/epinoiseoffset) instead*

**Comment by GlebIgorevich** [comment]
[LowRA](https://civitai.com/models/48139/lowra) is better than Noise Offset but this is not enough.

The same author has the paid extension that is integrated into the text2image process. It can do more than your extension, but you can reach the same results if you want. I think your project can be more popular with text2image integration and talking about that on Reddit.

**Comment by Haoming02** [comment]
Technically, between those 2 `LoRA`s, **LowRA** does a different thing from **Noise Offset**. 
afaik, **LowRA** is only able to generate dark images; **Noise Offset** is able to generate high contrast images, both dark and bright ones. *I could be wrong though as I didn't experiment with them much.*

And yeah, it's not that this Extension is dumb, it's more that ***I am dumb***. I haven't really looked into the codes to understand how to inject these into the actual pipeline. And well, since this Extension is right now rather stupid, I've yet to share it on any other sites at all.

**Comment by Haoming02** [comment]
*You know what, after some trial and error, I think I figure out something. Though I'll probably write it as a new Extension as they work very differently*

**Comment by GlebIgorevich** [comment]
Understand you. But if something will changed do this feature. It will be very helpful for community.

**Comment by Haoming02** [comment]
Introducing... [Vectorscope CC](https://github.com/Haoming02/sd-webui-vectorscope-cc)~
